### PR TITLE
add compile flag for switching to zenfs refactor version

### PR DESCRIPTION
**Pull request by weilewei**
adding WITH_ZENFS_REFACTOR for refactoring async support for metadata rollover

Usage: https://github.com/bzbd/zenfs/pull/46

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
<del>It seems that WITH_ZENFS has the same effect with WITH_ZENFS_REFACTOR, what about enable this flag by default when WITH_ZENFS is enabled?</del>

Maintaining two versions of ZenFS in a single repository might make everything hard. Unit tests and smoke tests will need to be run twice before every release. I think only keeping the refactored version is good enough.

**Comment by weilewei** [comment]
@skyzh that's true though, maybe we can keep the refactored version in a separate branch? Also CC @royguo @levisonchen for conversation.

**Comment by royguo** [comment]
For experimental purposes, please don’t change TerarkDB for now, just test on your local branch utils everything is settled. And we should add a CMakeLists under ZenFS itself to avoid TerarkDB changes later.

**Comment by weilewei** [comment]
@royguo ok, I will closed this PR since it is an experimental feature for now.

**Pull request closed without merging**
