### PR TITLE
Fix build.sh script

### LINKED ISSUE #89: Release build will shadow tests in build.sh
### Expected behavior
CMake will pick up `-DWITH_TESTS=ON` option when `WITH_TESTS=1 ./build.sh`.

### Actual behavior
CMake cannot pick up `-DWITH_TESTS` option when `WITH_TESTS=1 ./build.sh` because of `-DCMAKE_BUILD_TYPE=Release`.
```
$ WITH_TESTS=1 ./build.sh
build , with_tests = ON
...
[terarkdb] FORCE_RELEASE_BUILD = OFF, cmake_build_type = Release
[terarkdb] WITH_TOOLS = ON, WITH_ASAN = OFF, WITH_TESTS = OFF
[terarkdb] CMAKE_BUILD_TYPE=Release, BUILD_SUFFIX=r
...
```

Ref: https://github.com/bytedance/terarkdb/blob/1006943af96c49b36f6f794491340f628a3da16b/CMakeLists.txt#L41

### Steps to reproduce the behavior
```
git clone https://github.com/bytedance/terarkdb.git
cd terarkdb && git submodule update --init --recursive
WITH_TESTS=1 ./build.sh
```

### PR DESCRIPTION
**Pull request by v1siuol**
Fix #89

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
Thanks for your contribution. With `BUILD_TYPE` set to `DEBUG`, we can surely generate test artifacts. However, debug binaries run test very slow. In our testing environment, some test items may need as long as 5 minutes to run.

I'm thinking of changing this CMake option to enable tests in release mode. What do you think? @mm304321141 

```
CMAKE_DEPENDENT_OPTION(WITH_TESTS "build with tests" ON "CMAKE_BUILD_TYPE STREQUAL Debug" OFF) 
```

**Review by skyzh — APPROVED** [review]
After some internal discussions, it seems that tests are protected within `#ifdef` macros. These test binaries will never be successfully produced under release mode. Therefore, this patch looks reasonable to me.

* I suggest warning our user before and after the build, like "You are building TerarkDB with tests, so debug mode is enabled", something like this.
* You may take a look at `db_impl_debug.cc` and put them into testharness, therefore we could build release binary with those tests. Our main concern is that, those helper function symbols should not be exposed in static library, especially in release mode.

Thanks for your contribution!

**Comment by v1siuol** [comment]
Thanks for your feedback! 
> * I suggest warning our user before and after the build, like "You are building TerarkDB with tests, so debug mode is enabled", something like this.

Makes sense. Will do.

- [x] Add debug mode warning if building with test

> * You may take a look at `db_impl_debug.cc` and put them into testharness, therefore we could build release binary with those tests. Our main concern is that, those helper function symbols should not be exposed in static library, especially in release mode.

Yea I will take a look at it. My thought is to rewrite those `TEST_*` functions to an internal class, then make it as a friend class under private sestions to avoid public exposures. Something very similar to `write_batch_internal`. What do you think?

**Comment by skyzh** [comment]
> Yea I will take a look at it. My thought is to rewrite those TEST_* functions to an internal class, then make it as a friend class under private sestions to avoid public exposures. Something very similar to write_batch_internal. What do you think?

This might not work. In `libterarkdb.a`, private interface symbols might still be exposed (not sure about this). You may have a try in another PR, and just leave this PR for changing the test script.

If `WITH_TESTS` is not enabled, all tests and debug helpers should not be compiled into `libterarkdb.a` (especially in release mode). If we could meet this goal, any solution is okay.

**Comment by v1siuol** [comment]
^Rebase and add warnings

**Comment by v1siuol** [comment]
Thanks for your clarification. I will leave this PR for changing the test script. Let me know if you have any concerns. For example, BUILD_TYPE seems unused currently.

We can definitely start a new thread and discuss tests/release. Correct me if I am wrong, the goal here is to 1) build with tests in release mode, 2) without exposing tests and debug helpers to library.

I am concerning 1) because many tests depend on functions provided in `db_impl_debug.cc`, which will not exist in release mode (`#ifndef NDEBUG`).

Regarding 2), I am still learning cmake and visibility. But some common practice I observed is to define `<LIB>_EXPORT` macro, export stuffs we would like to expose (i.e., things under include/), and hide symbols by default. More reference: https://gcc.gnu.org/wiki/Visibility

**Comment by mm304321141** [comment]
LGTM

**Pull request merged**
